[package]
name = "collab-clicker-ssr-guest"
version = "0.0.0"
authors = ["someone"]
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
rquickjs = { version = "0.9.0", features = ["rust-alloc", "loader"] }
serde = { version = "^1.0.203", features = ["derive"] }
serde_json = "^1.0.117"
trailbase-wasm-guest = { workspace = true }
wstd = "0.5.3"
