packages:
  - 'client/testfixture/guests/typescript'
  - 'crates/assets/js/admin'
  - 'crates/assets/js/auth'
  - 'crates/assets/js/client'
  - 'crates/js-runtime/assets/runtime'
  - 'docs'
  - 'docs/examples/record_api_ts'
  - 'examples/blog/web'
  - 'examples/coffee-vector-search'
  - 'examples/coffee-vector-searc/guests/typescript'
  - 'examples/collab-clicker-ssr'
  - 'examples/collab-clicker-ssr/guests/typescript'
  - 'examples/data-cli-tutorial'
  - 'examples/tanstack-db-sync'
  - 'examples/wasm-guest-js'
  - 'examples/wasm-guest-ts'
  - 'guests/typescript'

sharedWorkspaceLockfile: true
linkWorkspacePackages: true
preferWorkspacePackages: true
preferOffline: false
preferFrozenLockfile: true
# strictPeerDependencies: false
disallowWorkspaceCycles: true
