[package]
name = "trailbase-wasm-common"
version = "0.1.0"
edition = "2024"
license = "OSL-3.0"
description = "WASM runtime for the TrailBase framework"
homepage = "https://trailbase.io"
exclude = [
  "**/node_modules/",
  "**/dist/",
]

[dependencies]
serde = { version = "^1.0.203", features = ["derive"] }
serde_json = "^1.0.117"
