name: release

on:
  push:
    tags:
      - "test-*.*.*"

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: macos-latest
            release_suffix: mac
          # - os: windows-latest
          #   release_suffix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends curl libssl-dev pkg-config libclang-dev protobuf-compiler libprotobuf-dev libsqlite3-dev
      - name: Install Dependencies
        if: matrix.os == 'macos-latest'
        run: |
            brew update && brew install pkg-config protobuf sqlite
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: PNPM install
        run: |
          pnpm i
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Rust Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          RUSTFLAGS="-C target-feature=+crt-static" cargo build --target x86_64-unknown-linux-gnu --release --bin trail && cp target/x86_64-unknown-linux-gnu/release/trail trail_${{ matrix.release_suffix }}
      - name: Rust Build Mac & Windows
        if: matrix.os != 'ubuntu-latest'
        run: |
          cargo build --release --bin trail && cp target/release/trail trail_${{ matrix.release_suffix }}
      # TODO: We should probably also run the tests before publishing?
      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          files: trail_${{ matrix.release_suffix }}
