name: release

on:
  push:
    tags:
      - "test-*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends curl libssl-dev pkg-config libclang-dev protobuf-compiler libprotobuf-dev libsqlite3-dev
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: PNPM install
        run: |
          pnpm i
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Rust build
        run: |
          RUSTFLAGS="-C target-feature=+crt-static" cargo build --target x86_64-unknown-linux-gnu --release --bin trail
      # We should probably also run the tests before publishing?
      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-unknown-linux-gnu/release/trail
