name: release
# TODO: We should probably also run the tests before publishing?

on:
  push:
    tags:
      - "test-*.*.*"

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Dependencies
        run: |
          sudo apt-get update && \
            sudo apt-get install -y --no-install-recommends curl libssl-dev pkg-config libclang-dev protobuf-compiler libprotobuf-dev libsqlite3-dev
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: PNPM install
        run: |
          pnpm i
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - name: Rust Build
        run: |
          RUSTFLAGS="-C target-feature=+crt-static" cargo build --target x86_64-unknown-linux-gnu --release --bin trail && \
            cp target/x86_64-unknown-linux-gnu/release/trail trail_${{  github.ref_name }}_linux_amd64
      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          files: trail_${{  github.ref_name }}"_linux_amd64

  release-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Dependencies
        run: |
            brew update && brew install pkg-config protobuf sqlite
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: PNPM install
        run: |
          pnpm i
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
      - name: Rust Build
        run: |
          cargo build --release --bin trail && \
            cp target/release/trail trail_${{  github.ref_name }}_darwin_arm64
      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          files: trail_${{  github.ref_name }}"_darwin_arm64
